// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYOUbZBvdCnbSXFt5MvkE3Lq8Xn32zmE',
    appId: '1:679415946256:web:424bb34812b4571c8a3e95',
    messagingSenderId: '679415946256',
    projectId: 'flutter-firebase-c1da0',
    authDomain: 'flutter-firebase-c1da0.firebaseapp.com',
    storageBucket: 'flutter-firebase-c1da0.appspot.com',
    measurementId: 'G-SV1FR9B1JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTtVobGNNVD60m6T9hV8V_QlbIAoeBj5Q',
    appId: '1:679415946256:android:e1a93602905315b28a3e95',
    messagingSenderId: '679415946256',
    projectId: 'flutter-firebase-c1da0',
    storageBucket: 'flutter-firebase-c1da0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKX0R8PXPa3EwtJh4WFNevayuGPuD05Q',
    appId: '1:679415946256:ios:7bfe7722d344c7868a3e95',
    messagingSenderId: '679415946256',
    projectId: 'flutter-firebase-c1da0',
    storageBucket: 'flutter-firebase-c1da0.appspot.com',
    iosClientId: '679415946256-3gk2ttmj8o4dga0ak6n1q0mi8ac5c3eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBiolerlate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKX0R8PXPa3EwtJh4WFNevayuGPuD05Q',
    appId: '1:679415946256:ios:7bfe7722d344c7868a3e95',
    messagingSenderId: '679415946256',
    projectId: 'flutter-firebase-c1da0',
    storageBucket: 'flutter-firebase-c1da0.appspot.com',
    iosClientId: '679415946256-3gk2ttmj8o4dga0ak6n1q0mi8ac5c3eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBiolerlate',
  );
}
